<?php
// $Id$

/**
 * @file
 * Defines a field type for referencing one node from another.
 */


// performance optimization: if not using a formatter, comment out the line.
// @TODO - is include_once deprecated across the board for module load?
include_once('biblioreference_formatter.inc');

/**
 * Implementation of hook_theme().
 */
function biblioreference_cck_theme() {
  return array(
    'biblioreference_cck_formatter_pubmed' => array(
      'arguments' => array('element' => NULL),
    ),
  );
}
