<?php
// $Id$

/**
 * @file biblioreference.module
 * [biblioreference] Add Biblio citation to a node (with special PubMed integration)
 * Originally called the add_citation module.  It replaces the
 * generic nodereference autocomplete widget with one specialized to use
 * additional Bibliography module specific fields to find biblio nodes.
 *
 * In addition to nodereference, we used noderefcreate.module (not in CVS)
 * as a module showing what must be taken to create a new nodereference widget.
 */

// functions in this include will move to gopubmed.module when Zaloni commits
require_once('pubmed_import.inc');
  
/**
 * Implementation of hook_menu().
 */
function biblioreference_menu() {
  $items = array();
  // @TODO - this should probably be in a separate module
  $items['admin/settings/biblio/import_pubmed'] = array(
    'title' => t('Import Pubmed'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('biblioreference_pubmed_import_form'),
    'access arguments' => array('create biblio'),  // not using the somewhat silly biblio_access wrapper function
    'file' => 'pubmed_import.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 8,
  );

  // @TODO - other location for menu?  change access arg.  admin include?
  $items['admin/settings/biblio/biblioreference'] = array(
    'title' => t('Biblioreference settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('biblioreference_settings_form'),
    'file' => 'biblioreference.admin.inc',
    'access arguments' => array('administer biblio'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 7,
  );
  
  $items['admin/settings/biblio/biblioreference/wipe'] = array(
    'title' => 'Clear index',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('biblioreference_wipe_confirm'),
    'access arguments' => array('administer biblio'),
    'type' => MENU_CALLBACK,
    'file' => 'biblioreference.admin.inc',
  );

  $items['biblioreference/add/citation'] = array(
    'title' => 'Add Citation',
    'page callback' => 'biblioreference_add_citation',
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('create biblio'),
    'file' => 'node.pages.inc',
    'file path' => drupal_get_path('module', 'node'),
  );
  
  $items['biblioreference/autocomplete'] = array(
    'title' => 'Biblioreference autocomplete',
    'page callback' => 'biblioreference_autocomplete',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  
  return $items;
}


/**
 * Menu callback; Retrieve a pipe delimited string of autocomplete suggestions for existing users
 */
function biblioreference_autocomplete($field_name, $string = '') {
//  $fields = content_fields();
//  $field = $fields[$field_name];
//  $match = isset($field['widget']['autocomplete_match']) ? $field['widget']['autocomplete_match'] : 'contains';
  $matches = array();

  $references = biblioreference_match_nodes($string);
  foreach ($references as $id => $row) {
    // Add a class wrapper for a few required CSS overrides.
    $matches[$row['title'] ." [nid:$id]"] = '<div class="reference-autocomplete">'. $row['rendered'] . '</div>';
  }
  drupal_json($matches);
}


/**
 * Menu callback for biblioreference add citation.
 */
function biblioreference_add_citation() {
  $output = '';
  $output .= '<h2>' . t('Reference Source') . '</h2>';
  $output .= '<ul>';
  $output .= '<li><h3>';
  $output .= t('Import Citations from PubMed');
  $output .= '</h3>';
  $output .= drupal_get_form('biblioreference_pubmed_import_form');
  $output .= '</li>';
  $output .= '<li><h3>';
  $output .= t('<a href="@url">Create a Reference that is not in PubMed</a>', array('@url' => url('node/add/biblio')));
  $output .= '</h3>';
  
  // @TODO  - of no use here, the choose reference type refreshes and leaves
  // the user on the same page -- which works, but is a confusing UI
//  $output .= drupal_get_form('biblioreference_embed_node_form_reuse', 'biblio');
 // @TODO send this all through a theme function
  return $output;
}

/**
 *
 */
function biblioreference_embed_node_form_reuse(&$form_state, $type = 'page') {
  global $user;

  $form = array();
  // Custom form top
  $form['biblioreference_top'] = array(
    '#type' => 'markup',
    '#title' => '<fieldset class=" collapsible">
    <legend>Create a Reference that is not in PubMed</legend>',
    '#default_value' => isset($form_state['values']['top_example']) ? $form_state['values']['top_example'] : '',
  );
  // Custom form bottom
  $form['biblioreference_bottom'] = array(
    '#type' => 'markup',
    '#title' => '</fieldset>',
    '#default_value' => isset($form_state['values']['bottom_example']) ? $form_state['values']['bottom_example'] : '',
    '#required' => TRUE,
  );
  
  if (node_access('create', $type)) {

    // Initialize new node:
    $node = array('uid' => $user->uid, 'name' => $user->name, 'type' => $type);

    $form += drupal_retrieve_form($type .'_node_form', $form_state, $node);
    drupal_prepare_form($type .'_node_form', $form, $form_state);
  }

  // Preserve the old #theme property.
  $form['#theme_saved'] = $form['#theme'];
  $form['#theme'] = 'embed_example_node_form_reuse';

  // Register an after build callback
// see https://more.zites.net/embed-a-node-form-with-drupal-6
// if we want to add our own submit handler to the form - using for markup now
// which means it wasn't necessary to add it to the form in the first place
//  $form['#after_build'][] = 'embed_example_after_build';

  return $form;
}


/**
 * Implementation of hook_theme().
 */
function biblioreference_theme() {
  return array(
    'biblioreference_node_form_reuse' => array(
      'arguments' => array('elements' => NULL),
    ),
  );
}

/**
 * Themes the form to put the custom parts of the form to the top and the bottom.
 */
function theme_biblioreference_node_form_reuse($form) {
  $top = drupal_render($form['biblioreference_top']);
  $bottom = drupal_render($form['biblioreference_bottom']);

  if (isset($form['#theme_saved'])) {
    // Apply the theme of the embedded form
    $form['#theme'] = $form['#theme_saved'];
    unset($form['#theme_used']);
  }

  return $top . drupal_render($form) . $bottom;
}

/**
 * Match biblio nodes based on index of words from title.
 *
 * Used in autocomplete function.
 *
 * The index could be extended to include words from the abstract or a keywords
 * field.
 */
function biblioreference_match_nodes($string, $match = 'starts_with', $limit = 10) {
  $string = trim($string, ' ');
  $words = search_index_split(trim($string,'\''));
  // the difference with these match operators is that they apply per word
  $match_operators = array(
    'contains' => "LIKE '%%%s%%'",
    'equals' => "= '%s'",
    'starts_with' => "LIKE '%s%%'",
  );
  
  $where_clause = "WHERE n.type = 'biblio' ";
  $where = array_fill(0, count($words), "bk.word {$match_operators[$match]}");
  
  if (!empty($where)) {
    $where_clause .= ' AND ('. implode(' OR ', $where) . ')';
  }
  
  // TODO: put back in db_rewrite_sql if it won't break anything
  // TODO: optimization: we may want to put title, authors, and journal title
  // into a separate table so that we can do it without joins-- especially if
  // the same table can be reused for theming purposes.
  $sql = "SELECT COUNT(bk.nid) AS matchcount, bk.nid AS nid, b.vid AS vid, n.title AS node_title, b.biblio_secondary_title AS journal_title, b.biblio_alternate_title AS journal_abbr, b.biblio_year AS year
          FROM {biblioreference_keyword} bk LEFT JOIN {node} n ON n.nid=bk.nid
          LEFT JOIN {biblio} b ON n.vid=b.vid " .
          $where_clause . " GROUP BY nid ORDER BY matchcount DESC";
 
  $result = db_query($sql, $words);
  $references = array();
  $i = 0;

  while (($node = db_fetch_object($result)) !== FALSE && $i < $limit) {
    $value = '';  // plain text for form field
    $rendered = '';  // HTML for drop-down selection
    $journal = ($node->journal_abbr) ? $node->journal_abbr : $node->journal_title;
    $authors =  biblioreference_authors_string($node->vid);
    $year = $node->year;
    $article = $node->node_title;
    
    $plain = $authors . ' ' . $year . ' ' . $node->journal_title
           . ' ' . $node->journal_abbr . ' ' . $article;
    $orig_words = explode(' ', $string);
    if (!_biblioreference_has_all_words($plain, $orig_words)) {
      continue;
    }
    
    $journal_r = biblioreference_autocomplete_highlight($journal, $orig_words);
    $authors_r = biblioreference_autocomplete_highlight($authors, $orig_words);
    $article_r = biblioreference_autocomplete_highlight($article, $orig_words);

    $value .= $authors . '. ' . $node->year;
    $rendered .= '<span class="nodereference-authors">';
    $rendered .= $authors_r . '.</span> ';
    if (!empty($year)) {
      $year_r = biblioreference_autocomplete_highlight($year, $words);
      $rendered .= '<span class="nodereference-year">' . $year_r . '.</span> ';
    }
    $value .= $journal . '. ' . $article . '.';
    $rendered .= '<span class="nodereference-journal">' . $journal_r . '</span> ';
    $rendered .= '<span class="description">' . $article_r . '</span>';
    
    $references[$node->nid] = array(
      'title' => $value,
      'rendered' => $rendered,
    );
    
    $i++;
  }
  
  return $references;
}

function biblioreference_autocomplete_form_value($nid) {
  $value = '';
  $sql = "SELECT b.vid AS vid, n.title AS node_title, b.biblio_secondary_title AS journal_title, b.biblio_alternate_title AS journal_abbr, b.biblio_year AS year
          FROM {node} n LEFT JOIN {biblio} b ON n.vid=b.vid
          WHERE n.nid = %d";
  $node = db_fetch_object(db_query($sql, $nid));
  $journal = ($node->journal_abbr) ? $node->journal_abbr : $node->journal_title;
  $authors = biblioreference_authors_string($node->vid);
  $value .= $authors . '. ' . $node->year;
  $value .= $journal . '. ' . $node->node_title . '.';
  // $value .= ' [nid:' . $node->nid . ']';  //@TODO replace with hidden field
  return $value;
}

/**
 * In the autocomplete results, highlight words searched for.
 *
 * @param string $rendered
 * @param array $words
 * @return string
 */
function biblioreference_autocomplete_highlight($rendered, $words) {
  foreach($words as $word) {
    $pattern = "/(?<!\<strong\>)\b($word)(?!\<\/strong\>|\w*\>)/iu";
    $replacement = '<strong>$1</strong>';
    $rendered = preg_replace($pattern, $replacement, $rendered);
  }
  return $rendered;
}

/**
 * Case-respecting case-insensitive search and replace to wrap/highlight text.
 *
 * Agaric Utility function.
 */
function biblioreference_au_str_highlight($search, $subject, $open, $close = NULL) {
  if ($close === NULL && substr($open, 0, 1) == '<') {
    // presume we want a closing tag.  Classed spans have to close themselves.
    $close = substr_replace($open, '/', 1, 0);
  }
  $length = strlen($search);
  $word_array = array();
  $pos = 0;
  $count = 0;
  while ($pos !== FALSE) {
    $pos = stripos($subject, $search, $pos);
    if ($pos !== FALSE) {
      $word_array[$count]['word'] = substr($subject, $pos, $length);
      $word_array[$count]['pos'] = $pos;
      $count++;
      $pos++;
    }
  }
  $i = $count-1;
  for ($i; $i >= 0; $i--) {
    $word = $open . $word_array[$i]['word'] . $close;
    $subject = substr_replace($subject, $word, $word_array[$i]['pos'], $length);
  }
  return $subject;
}

/**
 * Create a string of all authors for a given biblio node version id.
 */
function biblioreference_authors_string($vid) {
  $authors_string = '';
  $authors = array();
  $contributors = biblioreference_load_contributors($vid);
  foreach ($contributors as $author) {
    $authors[] = biblioreference_cse_format_author($author);
  }
  $authors_string = implode(', ', $authors);
  return $authors_string;
}

/**
 * Load contributors (authors) for a given biblio node version id.
 *
 * This will be faster than biblio_load_contributors() not because it selects
 * fewer fields but because it defines the fields and doesn't use an asterisk.
 */
function biblioreference_load_contributors($vid) {
  $contributors = array();
  $query = "SELECT lastname, firstname, initials, prefix
      FROM {biblio_contributor} bc
			INNER JOIN {biblio_contributor_data} bcd ON bc.cid=bcd.cid
			WHERE bc.vid=%d
			ORDER BY bc.rank ASC"; // do not change order of presentation
  $result = db_query($query, $vid);
  while ($creator = db_fetch_array($result)) {
    $contributors[] = $creator;
  }
  return $contributors;
}

/**
 * Format an author name to use last name and first initials, no commas.
 *
 * @param author
 *  An array of values for a bibliography author with keys matching db tables.
 *
 * @return
 *  A formatted string.
 *
 * Taken directly from biblio_style_cse.inc's _cse_format_author().
 * @TODO if we don't neet to change this at all, include that file and use its.
 */
function biblioreference_cse_format_author($author) {
  $format = $author['prefix'] . ' ' . $author['lastname'] . ' ';
  $format .= !empty ($author['firstname']) ? ' ' . drupal_substr($author['firstname'], 0, 1) : '';
  $format .= !empty ($author['initials']) ? str_replace(' ', '', $author['initials']) : '';
  return $format;
}

/**
 * Implementation of hook_form_FORMID_alter().
 */
function biblioreference_form_user_profile_form_alter(&$form, $form_state) {
  unset($form['profile']);
}

/**
 * Implementation of hook_form_alter().
 */
function biblioreference_form_alter(&$form, $form_state, $form_id) {
  // Run through all the elements on a node add/edit form
  if (isset($form['type'])) {
    $node = $form['#node'];
    if ($form['type']['#value'] .'_node_form' == $form_id) {
      $fields = content_fields();
      foreach ($form as $key => $item) {
        if (is_array($item)) {
          $type = $item['#type'];
          if ($type == 'fieldset') { // loop through all the subitems.
            foreach ($form[$key] as $subkey => $subitem) {
              biblioreference_alter_item($form[$key], $subkey, $subitem, $fields);
            }
          }
          else {
            biblioreference_alter_item($form, $key, $item, $fields);
          }
        }
      }
    }
  }
}

/**
 * .
 */
function biblioreference_alter_item(&$form, $key, $item, $fields) {
  $field_name = strstr($key, 'field_');
  if (isset($fields[$field_name]) && $fields[$field_name]['type'] == 'nodereference') {
    $type = $form['type']['#value'];
    $field = content_fields($field_name, $form['type']['#value']);
    if ($field['widget']['type'] == 'biblioreference_autocomplete') {
      // Add link to add new citation
      $suffix = '<div class="pdbiblio-add-new">';
      $suffix .= t('* If your reference is not in PD Biblio, <a href="@url" target="_BLANK">add a new citation in PDBiblio</a> manually.  This link will take you to a new window. After creating the reference, please remember to add it to the article.', array('@url' => url('biblioreference/add/citation')));
      $suffix .= '</div>';
      $form[$key]['#suffix'] = $suffix;
    }
  }
}

////////////////////////////////////////////////////////////////////////////
// Indexing related functions (for faster, more comprehensive autocomplete)
////////////////////////////////////////////////////////////////////////////

/**
 * Implements hook_cron().
 */
function biblioreference_cron() {
  $sql = 'SELECT * FROM {node} AS n JOIN {biblio} AS b USING (nid) '
       . 'WHERE b.nid NOT IN '
       . '(SELECT bk.nid FROM {biblioreference_keyword} AS bk) '
       . 'OR n.changed >= %d';
  $result = db_query_range($sql, variable_get('cron_last', 0), 0,
    variable_get('biblioreference_cron_limit', 0));
    
  while (($biblio = db_fetch_object($result)) !== FALSE) {
    // Note that search_index_split also calls search_simplify.
    $title_words = search_index_split($biblio->title);
    $name_words = biblioreference_index_split_bulk(
      biblioreference_get_contributor_names($biblio));
    $journal_words = biblioreference_index_split_bulk(
      biblioreference_get_journal($biblio));
    $words = array_unique(
      array_merge($title_words, $name_words, $journal_words));
    $values = '';
    foreach ($words as $word) {
      /* See http://svn.iic.harvard.edu/trac/pdonline/ticket/389 for the
       * reason why variable_get('minimum_word_size', 3) is not used here.
       * Words must be properly escaped in order to use multiple insert query
       * later.
       */
      if (drupal_strlen($word) > 0) {
        $word = db_escape_string($word);
        $values .= "('$word',$biblio->nid),";
      }
    }
    $values = rtrim($values, ',');
    $sql = "REPLACE INTO biblioreference_keyword (word,nid) VALUES $values";
    /* Drupal does not support multiple inserts, so escaping needs to be done
     * separately (see above). Here the 'unsafe' function can be used.
     */
    _db_query($sql);
  }
}

/**
 * Fetch the names of all contributors on a bibliography.
 *
 * @param $biblio
 *  An object containing the nid and vid of the bibliography node for which
 * author names are sought.
 *
 * @return
 *  An array of contributor full names.
 */
function biblioreference_get_contributor_names($biblio) {
  $contributor_names = array();
  $result = db_query("SELECT d.name FROM {biblio_contributor_data} d LEFT JOIN {biblio_contributor} c ON d.cid = c.cid WHERE c.nid = %d and c.vid = %d", array($biblio->nid, $biblio->vid));
  while ($contributor = db_fetch_array($result)) {
    $contributor_names[] = $contributor['name'];
  }
  return $contributor_names;
}

/**
 * Return the journal title and year associated with a Biblio node.
 *
 * This function could easily be rewritten/rebranded as 'biblio_get_values'
 *
 * @param $biblio
 *  An object containing at least the nid of a biblio node.
 * @return
 *  An array matching the values passed in.
 */
function biblioreference_get_journal($biblio, $fields = array('biblio_secondary_title', 'biblio_alternate_title', 'biblio_year')) {
  $values = array();
  $num_fields = count($fields);
  $columns = '';
  for ($i = 0; $i < $num_fields; $i++) {
    if ($i > 0) {
      $columns .= ', ';
    }
    $columns .= '%s';
  }
  $query = 'SELECT ' . $columns . ' FROM {biblio} WHERE vid = %d';
  $sql_args = $fields;
  $sql_args[] = $biblio->vid;
  $values = db_fetch_array(db_query($query, $sql_args));
  return $values;
}

/**
 * Split an array of strings into an array of words.
 *
 * Use search_index_split to take an array of strings and return an array of
 * all single words present.
 */
function biblioreference_index_split_bulk($strings) {
  $words = array();
  foreach ($strings as $string) {
    $words = array_merge($words, search_index_split($string));
  }
  return $words;
}

/**
 * Implementation of hook_nodeapi().
 *
 * We never remove words from a biblio's index, even though it may be edited
 * to change the title.  This is a feature, not a bug  ;-)
 */
function biblioreference_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  if ($node->type != 'biblio') {
    return;  // if it's not a biblio node, we're done with this
  }
  switch ($op) {
    case 'delete':
      db_query("DELETE FROM {biblioreference_keyword} WHERE nid = %d", $node->nid);
      break;
    case 'insert':
      if (variable_get('biblio_index', 0)) {
        biblioreference_cron();
      }
      break;
    case 'update':
      if (variable_get('biblio_index', 0)) {
        biblioreference_cron();
      }
      break;
  }
}

/**
 * Clears the index of biblioreference nodes and sets re-indexing to start.
 */
function biblioreference_index_wipe() {
  db_query('DELETE FROM {biblioreference_keyword}');
}

/**
 * Implementation of hook_theme_registry_alter().
 */
function biblioreference_theme_registry_alter($theme_registry) {
  if (!empty($theme_registry['biblio_tagged_link'])) {
    $theme_registry['biblio_tagged_link']['function'] = 'biblioreference_theme_biblio_tagged_link';
  }
}

/**
 * Creates a link to export a node (or view) in EndNote Tagged format.
 *
 * Overrides biblio/biblio_theme.inc's theme_biblio_tagged_link().
 *
 * @param $base this is the base url (defaults to /biblio)
 * @param $nid  the node id, if NULL then the current view is exported
 * @return  a link (<a href=...>Endnote</a>)
 */
function biblioreference_theme_biblio_tagged_link($base, $nid = NULL) {
  if (module_exists('popups') && !empty($nid)) {
    $output .= l(t("Endnote"), "$base/export/tagged/$nid/popup", array('attributes'=>array('class' => 'popups', 'title' => t("Click to get the EndNote Tagged output "))));
  } else {
    $output .= l(t("Endnote"), "$base/export/tagged/$nid", array('attributes'=>array('title' => t("Click to download the EndNote Tagged formated file"))));
  }
  return $output;
}

/**
 * Apply a bibliographic style to the node
 *
 *
 * @param $node
 *   An object containing the node data to render
 * @param $base
 *   The base URL of the biblio module (defaults to /biblio)
 * @param $inline
 *   A logical value indicating if this is being rendered within the
 *   Drupal framwork (false) or we are just passing back the html (true)
 * @return
 *   The styled biblio entry
 */
function biblioreference_style_biblio($node, $base = 'biblio', $inline = false) {
  $contrib_array = _biblioreference_format_authors($node->biblio_contributors, $inline);
  $authors = $contrib_array[1];
  $output .= '<span class="biblio-authors">' . $authors . "</span>.&nbsp; \n";
  switch ($node->biblio_type) {

    default :
      if (isset ($node->biblio_year)) {
        $output .= check_plain($node->biblio_year) . ".&nbsp;&nbsp;";
      }
      $output .= '<span class="biblio-title">';
      $output .= $inline ? l("$node->title", "$base/viewinline/$node->nid") : l("$node->title", "node/$node->nid");
      $output .= ". </span> \n";
      $output .= (!empty ($node->biblio_secondary_title)) ? check_plain($node->biblio_secondary_title) . '. ' : '';
      $output .= (!empty ($node->biblio_volume)) ? check_plain($node->biblio_volume) : '';
      $output .= (!empty ($node->biblio_issue)) ? '(' . check_plain($node->biblio_issue) . ')' : '';
      $output .= (!empty ($node->biblio_pages)) ? ':' . str_replace(" ", "", check_plain($node->biblio_pages)) . '.' : '';
      break; // generic
  }
  /*  if ($node->biblio_date) $output .= ', '. check_plain($node->biblio_date);
    if ($node->biblio_number) $output .= ', Number '. check_plain($node->biblio_number);
  
    if ($node->biblio_place_published) $output .= ', '. check_plain($node->biblio_place_published);
  */
  return $output;
}

function _biblioreference_format_authors($contributors, $inline = FALSE) {
  if (count($contributors)) {
    foreach ($contributors as $key => $author) {
      $format = $author['prefix'] . ' ' . $author['lastname'] . ' ';
      $format .= !empty ($author['firstname']) ? ' ' . drupal_substr($author['firstname'], 0, 1) : '';
      $format .= !empty ($author['initials']) ? str_replace(' ', '', $author['initials']) : '';
      if (variable_get('biblio_author_links', 1)) {
        $base = variable_get('biblio_base', 'biblio');
        $format = _biblio_author_link($format, $author['cid'], $base, $inline);
      }
      $author_array[$author['auth_catagory']] .= (!empty ($author_array[$author['auth_catagory']])) ? ', ' . $format : $format;
    }
  }
  if (count($author_array)) {
    return $author_array;
  } else {
    return array (
      1 => t('No author information available')
    );
  }
}

/**
 * Returns TRUE if all words are in the given result, FALSE otherwise.
 * Helper function for biblioreference_match_nodes().
 *
 * @param string $result
 * @param array $words
 * @return bool
 */
function _biblioreference_has_all_words($result, $words) {
  foreach ($words as $word) {
    if (stripos($result, $word) === FALSE) return FALSE;
  }
  return TRUE;
}
